# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlR8xr8-0wxmi8PvOX3kzisaaWI2fR1W
"""

#import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/Microsoft Dataset.csv')

print("first few rows of the dataset:")
print(data.head)

print("\nMissing values in the dataset are: ")
print(data.isnull().sum())

mean_price= data['Close'].mean()
median_price=data['Close'].median()
std_dev_price= data['Close'].std
print(f"mean closing price: {mean_price}")
print(f"median closing price: {median_price}")
print(f"Standard deviation closing price: {std_dev_price}")

plt.figure(figsize=(10,6))
sns.histplot(data['Close'],kde=True, bins=30)
plt.xlabel('Closing price')
plt.ylabel('Frequency')
plt.title('Distribution of Microsoft Stock Closing prices')
plt.show